### ISSUE TITLE
ReferenceError: SpiceMainConn is not defined

### ISSUE THREAD

**Issue by hot22shot** [muayyad-alsadi/containerized-xorg-spice#1]
Hello,

I tried to use the html5 client and got this error when trying to connect on the spice-html container on port 5959 :
![SPICE](https://user-images.githubusercontent.com/33095930/54116429-0c0e0180-43ef-11e9-924f-b8cc61f2458f.png)

I used the docker-compose.yml and docker-compose up command to build the containers.

Thank you for any help !

**Comment by muayyad-alsadi** [comment]
I've tried it and it works fine,

the docker-compose publishes spice-html client on 8080 not 5959, make sure you use that client

the documentation says

```
git clone https://github.com/muayyad-alsadi/containerized-xorg-spice.git
cd containerized-xorg-spice
docker-compose up
```

Then open your browser on port 8080 like this

end of quote.

if you look at the screen shot you see the location is `http://localhost:8080/spice.html`
